site_name: Talentemp Financial
docs_dir: docs_dir
site_dir: docs
nav:
  - DigitalTolk: index.md
  - Talentemp:
    - Pricelist and Rules: tnt.md
    - Pricelist Rule Conditions: conditions.md
  - Playground:
    - Common Flows: playground.md
    - Addita Age Factor: addita.md
  - To Do: todo.md
theme: material
extra_javascript:
  - https://blueimp.github.io/JavaScript-MD5/js/md5.js
  - javascripts/password.js
